apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditscore-api
  labels:
    app: creditscore
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creditscore
  template:
    metadata:
      labels:
        app: creditscore
        env: dev
    spec:
      containers:
        - name: creditscore-api
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/creditscore:dev
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "DEV"
---
apiVersion: v1
kind: Service
metadata:
  name: creditscore-svc
spec:
  selector:
    app: creditscore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
