name: Deploy DEV

on:
  push:
    branches: ["develop"]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: AWS Auth (DEV)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/github-dev-role
          aws-region: us-east-1

      - name: Update kubeconfig DEV
        run: |
          aws eks update-kubeconfig --name creditscore-dev --region us-east-1

      - name: Apply K8s manifests DEV
        run: |
          kubectl apply -f infra/k8s/dev/
