name: Deploy UAT

on:
  push:
    branches: ["uat"]

jobs:
  deploy-uat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: AWS Auth (UAT)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/github-uat-role
          aws-region: us-east-1

      - name: Update kubeconfig UAT
        run: |
          aws eks update-kubeconfig --name creditscore-uat --region us-east-1

      - name: Apply K8s manifests UAT
        run: |
          kubectl apply -f infra/k8s/uat/
